image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: ignore
  - port: 4000
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: ignore
  - port: 24678
    onOpen: ignore

tasks:
  - before: |
      npm i -g pnpm
    init: |
      pnpm i
      pnpm build
      pnpm test
    command: |
      git config core.hookspath .githooks
