packages:
  - 'packages/*'
  - 'sites/*'
  - 'packages/adapter-static/test/apps/*'
  - 'packages/kit/test/apps/*'
  - 'packages/kit/test/prerendering/*'
  - 'packages/create-svelte/templates/*'
  - 'packages/create-svelte/.test-tmp/*'
