[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify/build/"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"

[dev]
# Disable svelte-kit dev so we can test functions
framework = "#static"
