[build]
  command = "npm run build && rm -rf /dev/null"
  publish = ".svelte-kit/netlify/build/"
  functions = ".svelte-kit/netlify/functions/"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"
