[build]
  command = "npm run build"
  publish = ".svelte-kit/netlify/build/"
  functions = ".svelte-kit/netlify/functions/"

[build.environment]
  NPM_FLAGS="--prefix=/opt/buildhome/hn.svelte.dev"

[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"
